# Header
menu:
  Home: /
  Archives: /archives
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics: UA-127412653-1
gauges_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:

# Show PV/UV of the website/page with busuanzi.
# Get more information on http://ibruce.info/2015/04/04/busuanzi/
busuanzi_count:
  # count values only if the other configs are false
  enable: true
  # custom uv span for the whole site
  site_uv: true
  site_uv_header: <i class="fa fa-user">本站访客数</i>
  site_uv_footer: <i class="fa fa-user">人次</i>
  # custom pv span for the whole site
  site_pv: true
  site_pv_header: <i class="fa fa-eye">本站总访问量</i>
  site_pv_footer: <i class="fa fa-eye">次</i>
  # custom pv span for one page only
  page_pv: true
  page_pv_header: <i class="fa fa-file-o">本文总阅读量</i>
  page_pv_footer: <i class="fa fa-file-o">次</i>
  