# Header Menu
menu:
  Home: /
  Archives: /archives
  # change github and email values to your own addresses
  Github: https://github.com/apomelo
  Email: mailto:apomeloc@gmail.com
rss: /atom.xml

# Set to false to disable banner
use_header_cover: true

# URL of the banner image
# Put your custom banner image under
# the theme's img folder: your-blog/themes/minimal-dual/source/img/
# and modify index_cover's value like so:
# index_cover: /img/your-custom-banner.jpg
# or
# Put your custom banner image under
# your blog's images folder: your-blog/source/images/
# and modify index_cover's value like so:
# index_cover: /images/your-custom-banner.jpg
# or
# Specify an online resource like so:
# index_cover: http://somewhere.com/path/to/banner.jpg
index_cover: /img/5a1670f9b52a83.jpg

widgets:
- category
- tag
- archive

# widget behavior
archive_type: 'monthly'
show_count: false

# favicon
favicon: /favicon.ico

# Google Analytics Tracking ID
google_analytics: UA-127412653-1

# Show PV/UV of the website/page with busuanzi.
# Get more information on http://ibruce.info/2015/04/04/busuanzi/
busuanzi_count:
  # count values only if the other configs are false
  enable: true
  # custom uv span for the whole site
  site_uv: true
  site_uv_header: <i class="fa fa-user">本站访客数</i>
  site_uv_footer: <i class="fa fa-user">人次</i>
  # custom pv span for the whole site
  site_pv: true
  site_pv_header: <i class="fa fa-eye">本站总访问量</i>
  site_pv_footer: <i class="fa fa-eye">次</i>
  # custom pv span for one page only
  page_pv: true
  page_pv_header: <i class="fa fa-file-o">本文总阅读量</i>
  page_pv_footer: <i class="fa fa-file-o">次</i>
  